spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mysql2018
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    root: info
    cn.dianshi: debug
  file:
    name: log/blog-dev.log
