spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mysql2018
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
logging:
  level:
    root: warn
    cn.dianshi: info
  file:
    name: log/blog-pro.log

server:
  port:8081
